---
- name: Configure interface on Cisco IOS (mock)
  hosts: R1
  gather_facts: no

  vars:
    interface_name: ""
    interface_ip: ""
    interface_mask: ""

  tasks:
    - name: Render interface configuration
      copy:
        dest: "automation/ansible/rendered/{{ inventory_hostname }}_{{ interface_name }}.cfg"
        content: |
          interface {{ interface_name }}
           ip address {{ interface_ip }} {{ interface_mask }}
           no shutdown